language: go
go: 1.10.x
services: docker
before_install:
  - docker volume rm $(docker volume ls -qf dangling=true)
  - make setup
install:
  - make start
before_script:
  - make before_check
script:
  - make check
after_success:
  - make after_check