language: node_js
node_js: lts/carbon
services: docker
before_install:
  - make setup
  - npm i -g coveralls
install:
  - make start
script:
  - make check
after_success:
  - make lcov | tail -n +2 > coverage.lcov
  - sed -i 's/\/github.com\/alcmoraes\/go-data-integration-challenge/\/home\/travis\/build\/alcmoraes\/go-data-integration-challenge/g' coverage.lcov
  - cat coverage.lcov | coveralls